import Foundation
import SwiftData

@Model
final class CommunicationLog {
    var commType: CommunicationType
    var subject: String
    var bodyText: String
    var sentAt: Date
    var wasAutoGenerated: Bool

    // Relationships
    var client: Client?

    init(
        commType: CommunicationType = .email,
        subject: String = "",
        bodyText: String = "",
        sentAt: Date = Date(),
        wasAutoGenerated: Bool = false
    ) {
        self.commType = commType
        self.subject = subject
        self.bodyText = bodyText
        self.sentAt = sentAt
        self.wasAutoGenerated = wasAutoGenerated
    }
}

enum CommunicationType: String, Codable, CaseIterable {
    case email = "Email"
    case sms = "SMS"
    case phone = "Phone Call"
    case inPerson = "In Person"
    case note = "Internal Note"

    var systemImage: String {
        switch self {
        case .email: "envelope.fill"
        case .sms: "message.fill"
        case .phone: "phone.fill"
        case .inPerson: "person.fill"
        case .note: "note.text"
        }
    }
}
